apiVersion: v1
kind: ResourceQuota
metadata:
  name: recon-datastores-quota
  namespace: recon-datastores
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
