apiVersion: v1
kind: Secret
metadata:
  name: minio-root-credentials
  namespace: recon-datastores
type: Opaque
stringData:
  root-user: "recon-minio-admin"
  root-password: "change-me-minio-root-pass"
