apiVersion: v1
kind: Secret
metadata:
  name: postgresql-app-credentials
  namespace: recon-datastores
type: Opaque
stringData:
  postgres-password: "change-me-postgres-admin-pass"
  password: "change-me-recon-app-pass"
